=== UO299855/MotoGP-Desktop/MotoGP-Desktop/xml/circuito.dtd
<!ELEMENT circuito (nombre, longitud-circuito, pais, anchura-media, fecha, hora, vueltas, patrocinador, referencias, fotografias, videos, origen, tramos, vencedor, clasificados)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT longitud-circuito (#PCDATA)>
<!ELEMENT anchura-media (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT vueltas (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT patrocinador (#PCDATA)>
<!ELEMENT referencias (referencia+)> <!-- mínimo 3-->
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT fotografias (fotografia+)> <!-- Entre 1 y 5-->
<!ELEMENT fotografia (#PCDATA)>
<!ELEMENT videos (video+)> <!-- Galería de vídeos (entre 1 y 3)-->
<!ELEMENT video (#PCDATA)>
<!ELEMENT origen (coordenadas)>
<!ELEMENT coordenadas (longitud, latitud, altitud)> <!-- Punto de origen (latitud, longitud, altitud)-->
<!ELEMENT tramos (tramo+)>
<!ELEMENT tramo (distancia, coordenadas)>
<!ELEMENT distancia (#PCDATA)>

<!ELEMENT longitud (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>
<!ELEMENT vencedor (tiempo-victoria)>
<!ELEMENT tiempo-victoria (#PCDATA)>

<!--3 primeros clasificados (después de la carreda) en la tabla global, no solo en el circuito de Indonesia -->
<!ELEMENT clasificados (clasificado+)>
<!ELEMENT clasificado (#PCDATA)>

<!ATTLIST anchura-media unidades CDATA #REQUIRED>
<!ATTLIST longitud-circuito unidades CDATA  #REQUIRED>
<!ATTLIST longitud unidades CDATA #REQUIRED>
<!ATTLIST latitud unidades CDATA #REQUIRED>
<!ATTLIST altitud unidades CDATA #REQUIRED>
<!ATTLIST vencedor nombre CDATA #REQUIRED>
<!ATTLIST tiempo-victoria unidades CDATA #REQUIRED>
<!ATTLIST clasificado puesto CDATA #REQUIRED>
<!ATTLIST clasificado puntos CDATA #REQUIRED>
<!ATTLIST distancia unidades CDATA #REQUIRED>
<!ATTLIST tramo sector CDATA #REQUIRED>

<!-- Entre 1 y 5, en máquina local-->
<!-- usar unos 28 puntos para los tramos, y clasificarlo según sectores-->
<!-- jugar con "tramos" (plural) que contiene a varios "tramo" (singular)-->

=== UO299855/MotoGP-Desktop/MotoGP-Desktop/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">
<!-- PONER METROS CON TODAS LAS LETRAS-->
 <circuito>
    <nombre>Pertamina Mandalika Circuit</nombre>
    <longitud-circuito unidades="metros">4301</longitud-circuito>
    <pais>Indonesia</pais>
    <anchura-media unidades="metros">15</anchura-media>
    <fecha>05/10/2025</fecha>
    <hora>9:00</hora>
    <vueltas>27</vueltas>
    <patrocinador>Pertamina</patrocinador>
    <referencias>
        <referencia>https://www.motogp.com/es/calendar/2025/event/indonesia/c4def1f2-c288-4eab-9461-7acda49e765a?tab=circuit-info</referencia>
        <referencia>https://es.wikipedia.org/wiki/Circuito_Urbano_Internacional_de_Mandalika</referencia>
        <referencia>Referencia 3</referencia>
    </referencias>
    <fotografias>
        <fotografia>Foto 1</fotografia>
        <fotografia>Foto 2</fotografia>
        <fotografia>Foto 3</fotografia>
    </fotografias>
    <videos>
        <video>multimedia/circuito/video2.mp4</video>
        <video>multimedia/circuito/video2.mp4</video>        
    </videos>
    <origen>
        <coordenadas>
            <longitud unidades = "grados" >116.303333</longitud>
            <latitud unidades = "grados">-8.895555</latitud>
            <altitud unidades="metros">9.25</altitud>
        </coordenadas>
    </origen>
    <tramos>
        <tramo sector="I1">
            <distancia unidades="metros">200</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3072222</longitud>
                <latitud unidades="grados">-8.8944444</latitud>
                <altitud unidades="metros">8.59</altitud>
            </coordenadas>
        </tramo>
        <tramo sector="I2">
            <distancia unidades="metros">155.68</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3086111</longitud>
                <latitud unidades="grados">-8.8941667</latitud>
                <altitud unidades="metros">8.23</altitud>
            </coordenadas>
        </tramo>
        <tramo sector="I3">
            <distancia unidades="metros">0.49</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3086111</longitud>
                <latitud unidades="grados">-8.8941667</latitud>
                <altitud unidades="metros">7.74</altitud>
            </coordenadas>
        </tramo>
        <tramo sector="I4">
            <distancia unidades="metros">43.42</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3083333</longitud>
                <latitud unidades="grados">-8.8944444</latitud>
                <altitud unidades="metros">7.68</altitud>
            </coordenadas>
        </tramo>
        <tramo sector="I5">
            <distancia unidades="metros">68.41</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3088889</longitud>
                <latitud unidades="grados">-8.8941667</latitud>
                <altitud unidades="metros">8.35</altitud>
            </coordenadas>
        </tramo>
        <tramo sector="I6">
            <distancia unidades="metros">248.98</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3086111</longitud>
                <latitud unidades="grados">-8.8963889</latitud>
                <altitud unidades="metros">7.68</altitud>
            </coordenadas>
        </tramo>
        <tramo sector="I7">
            <distancia unidades="metros">0.47</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3086111</longitud>
                <latitud unidades="grados">-8.8963889</latitud>
                <altitud unidades="metros">7.21</altitud>
            </coordenadas>
        </tramo>
        <tramo sector="I8">
            <distancia unidades="metros">86.84</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3091667</longitud>
                <latitud unidades="grados">-8.8958333</latitud>
                <altitud unidades="metros">7.83</altitud>
            </coordenadas>
        </tramo>
        <tramo sector="I9">
            <distancia unidades="metros">196.33</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3077778</longitud>
                <latitud unidades="grados">-8.8969444</latitud>
                <altitud unidades="metros">7.54</altitud>
            </coordenadas>
        </tramo>
        <tramo sector="I10">
            <distancia unidades="metros">130.26</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3086111</longitud>
                <latitud unidades="grados">-8.8961111</latitud>
                <altitud unidades="metros">7.52</altitud>
            </coordenadas>
        </tramo>
        <tramo sector="I11">
            <distancia unidades="metros">43.42</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3083333</longitud>
                <latitud unidades="grados">-8.8963889</latitud>
                <altitud unidades="metros">7.52</altitud>
            </coordenadas>
        </tramo>
        <tramo sector="I12">
            <distancia unidades="metros">61.78</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3083333</longitud>
                <latitud unidades="grados">-8.8969444</latitud>
                <altitud unidades="metros">7.41</altitud>
            </coordenadas>
        </tramo>
        <tramo sector="I13">
            <distancia unidades="metros">137.80</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3077778</longitud>
                <latitud unidades="grados">-8.8980556</latitud>
                <altitud unidades="metros">7.21</altitud>
            </coordenadas>
        </tramo>
        <tramo sector="I14">
            <distancia unidades="metros">130.26</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3086111</longitud>
                <latitud unidades="grados">-8.8988889</latitud>
                <altitud unidades="metros">7.37</altitud>
            </coordenadas>
        </tramo>
        <tramo sector="I15">
            <distancia unidades="metros">30.52</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3088889</longitud>
                <latitud unidades="grados">-8.8988889</latitud>
                <altitud unidades="metros">7.22</altitud>
            </coordenadas>
        </tramo>
        <tramo sector="I16">
            <distancia unidades="metros">30.52</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3091667</longitud>
                <latitud unidades="grados">-8.8988889</latitud>
                <altitud unidades="metros">7.15</altitud>
            </coordenadas>
        </tramo>
        <tramo sector="I17">
            <distancia unidades="metros">187.82</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3088889</longitud>
                <latitud unidades="grados">-8.9005556</latitud>
                <altitud unidades="metros">6.44</altitud>
            </coordenadas>
        </tramo>
        <tramo sector="I18">
            <distancia unidades="metros">43.42</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3091667</longitud>
                <latitud unidades="grados">-8.9002778</latitud>
                <altitud unidades="metros">6.46</altitud>
            </coordenadas>
        </tramo>
        <tramo sector="I19">
            <distancia unidades="metros">97.56</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3088889</longitud>
                <latitud unidades="grados">-8.9011111</latitud>
                <altitud unidades="metros">6.60</altitud>
            </coordenadas>
        </tramo>
        <tramo sector="I20">
            <distancia unidades="metros">173.68</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3077778</longitud>
                <latitud unidades="grados">-8.9022222</latitud>
                <altitud unidades="metros">6.61</altitud>
            </coordenadas>
        </tramo>
        <tramo sector="I21">
            <distancia unidades="metros">43.42</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3075000</longitud>
                <latitud unidades="grados">-8.9025000</latitud>
                <altitud unidades="metros">6.61</altitud>
            </coordenadas>
        </tramo>
        <tramo sector="I22">
            <distancia unidades="metros">30.52</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3072222</longitud>
                <latitud unidades="grados">-8.9025000</latitud>
                <altitud unidades="metros">6.54</altitud>
            </coordenadas>
        </tramo>
        <tramo sector="I23">
            <distancia unidades="metros">91.55</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3063889</longitud>
                <latitud unidades="grados">-8.9025000</latitud>
                <altitud unidades="metros">7.06</altitud>
            </coordenadas>
        </tramo>
        <tramo sector="I24">
            <distancia unidades="metros">68.40</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3058333</longitud>
                <latitud unidades="grados">-8.9027778</latitud>
                <altitud unidades="metros">6.91</altitud>
            </coordenadas>
        </tramo>
        <tramo sector="I25">
            <distancia unidades="metros">68.90</distancia>
            <coordenadas>
                <longitud unidades="grados">116.3055556</longitud>
                <latitud unidades="grados">-8.9033333</latitud>
                <altitud unidades="metros">6.91</altitud>
