=== UO299855/MotoGP-Desktop/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified" targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:all>
				<xs:element ref="nombre"/>
				<xs:element ref="longitud-circuito" />
				<xs:element ref="localidad"/>
				<xs:element ref="pais" />
				<xs:element ref="anchura-media" />
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element ref="vueltas" />
				<xs:element ref="patrocinador" />
				<xs:element ref="referencias" />
				<xs:element ref="fotografias" />
				<xs:element ref="videos" />
				<xs:element ref="origen" />
				<xs:element ref="tramos" />
				<xs:element ref="vencedor" />
				<xs:element ref="clasificados" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="longitud-circuito">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:positiveInteger">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="tiempo-victoria" type="xs:duration" />
	<xs:element name="anchura-media">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:positiveInteger">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="hora" type="xs:time" />
	<xs:element name="vueltas" type="xs:positiveInteger" />
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="patrocinador" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="titulo" type="xs:string" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
	</xs:element>
	<xs:element name="fotografias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="descripcion" type="xs:string" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
	</xs:element>
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="descripcion" type="xs:string" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
	</xs:element>
	<xs:element name="origen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenadas" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:all>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:all>
				<xs:element ref="distancia" />
				<xs:element ref="coordenadas" />
			</xs:all>
			<xs:attribute name="sector" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="tipoDistancia">
		<xs:restriction base="xs:decimal">
			<xs:minExclusive value="0"/>
    		<xs:maxInclusive value="500"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="tipoPuesto">
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="3"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoDistancia">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="tipoLongitud">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-180"/>
    		<xs:maxInclusive value="180"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoLongitud">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="tipoLatitud">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-90"/>
    		<xs:maxInclusive value="90"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="latitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoLatitud">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="tipoAltitud">
		<xs:restriction base="xs:decimal">
			<xs:minExclusive value="0"/>
    		<xs:maxInclusive value="1000"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoAltitud">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="vencedor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tiempo-victoria" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificados">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="3" ref="clasificado" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificado">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="puesto" type="tipoPuesto" use="required" />
					<xs:attribute name="puntos" type="xs:positiveInteger" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== UO299855/MotoGP-Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito xsi:schemaLocation="http://www.uniovi.es circuito.xsd"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="http://www.uniovi.es">
    <nombre>Pertamina Mandalika Circuit</nombre>
    <longitud-circuito unidades="metros">4301</longitud-circuito>
    <localidad>Baturiti</localidad>
    <pais>Indonesia</pais>
    <anchura-media unidades="metros">15</anchura-media>
    <fecha>2025-10-05</fecha>
    <hora>09:00:00</hora>
    <vueltas>27</vueltas>
    <patrocinador>Pertamina</patrocinador>
    <referencias>
        <referencia titulo="Página oficial de MotoGP">https://www.motogp.com/es/calendar/2025/event/indonesia/c4def1f2-c288-4eab-9461-7acda49e765a?tab=circuit-info</referencia>
        <referencia titulo="DAZN motor">https://www.dazn.com/es-ES/news/motor/circuito-pertamina-mandalika-donde-esta-como-es-caracteristicas-como-llegar-fotos-escenario-gp-indonesia-mundial-motogp/1k0kpjd6k9hzd1em3dyu97u7db</referencia>
        <referencia titulo="Diario de Mallorca">https://www.diariodemallorca.es/deportes/2025/10/03/analisis-circuito-mandalika-curiosidades-122225493.html</referencia>
    </referencias>
    <fotografias>
        <fotografia descripcion="Vista arérea del circuito de Pertamina Mandalika">multimedia/circuito/panorama.jpg</fotografia>
        <fotografia descripcion="Diego Moreira haciendo un caballito en el circuito">multimedia/circuito/caballito.jpg</fotografia>
        <fotografia descripcion="Joan Mir en el circuito Pertamina Mandalika durante la temporada 2025">multimedia/circuito/mir.jpg</fotografia>
    </fotografias>
    <videos>
        <video descripcion="Fermín Aldeguer celebra su victoria en el Gran Premio de Indonesia 2025">multimedia/circuito/vencedor.mp4</video>
        <video descripcion="Vista en primera persona de una vuelta al circuito">multimedia/circuito/pov.mp4</video>        
    </videos>
    <origen>
        <coordenadas>
            <latitud unidades = "grados">-8.895555555555555</latitud>
            <longitud unidades = "grados" >116.30361111111111</longitud>
            <altitud unidades="metros">9.14</altitud>
        </coordenadas>
    </origen>
    <vencedor nombre = "Fermín Aldeguer">
        <tiempo-victoria>PT2467.651S</tiempo-victoria>
    </vencedor>
    <clasificados>
        <clasificado puesto="1" puntos="545">Marc Márquez</clasificado>
        <clasificado puesto="2" puntos="362">Alex Márquez</clasificado>
        <clasificado puesto="3" puntos="274">Francesco Bagnaia</clasificado>
    </clasificados>
    <tramos>
        <tramo sector="S1">
            <coordenadas>
                <latitud unidades="grados">-8.895656518635604</latitud>
                <longitud unidades="grados">116.30371432947197</longitud>
                <altitud unidades="metros">9.15</altitud>
            </coordenadas>
            <distancia unidades="metros">129.50</distancia>
        </tramo>
        <tramo sector="S1">
            <coordenadas>
                <latitud unidades="grados">-8.895338520556606</latitud>
                <longitud unidades="grados">116.30484750317663</longitud>
                <altitud unidades="metros">8.43</altitud>
            </coordenadas>
            <distancia unidades="metros">308.23</distancia>
        </tramo>
        <tramo sector="S1">
            <coordenadas>
                <latitud unidades="grados">-8.894587195876298</latitud>
                <longitud unidades="grados">116.30754607415531</longitud>
                <altitud unidades="metros">8.66</altitud>
            </coordenadas>
            <distancia unidades="metros">33.28</distancia>
        </tramo>
        <tramo sector="S1">
            <coordenadas>
                <latitud unidades="grados">-8.894506000738957</latitud>
                <longitud unidades="grados">116.30783744095004</longitud>
                <altitud unidades="metros">8.34</altitud>
            </coordenadas>
            <distancia unidades="metros">18.72</distancia>
        </tramo>
        <tramo sector="S1">
            <coordenadas>
                <latitud unidades="grados">-8.894461503716514</latitud>
                <longitud unidades="grados">116.30800169309674</longitud>
                <altitud unidades="metros">8.68</altitud>
            </coordenadas>
            <distancia unidades="metros">15.11</distancia>
        </tramo>
        <tramo sector="S1">
            <coordenadas>
                <latitud unidades="grados">-8.894481317746894</latitud>
                <longitud unidades="grados">116.3081375907318</longitud>
                <altitud unidades="metros">8.35</altitud>
            </coordenadas>
            <distancia unidades="metros">20.02</distancia>
        </tramo>
        <tramo sector="S1">
            <coordenadas>
                <latitud unidades="grados">-8.894547432842202</latitud>
                <longitud unidades="grados">116.30830707650301</longitud>
                <altitud unidades="metros">8.28</altitud>
            </coordenadas>
            <distancia unidades="metros">13.81</distancia>
        </tramo>
        <tramo sector="S1">
            <coordenadas>
                <latitud unidades="grados">-8.89463335346602</latitud>
                <longitud unidades="grados">116.3083981296769</longitud>
                <altitud unidades="metros">8.07</altitud>
            </coordenadas>
            <distancia unidades="metros">15.14</distancia>
        </tramo>
        <tramo sector="S1">
            <coordenadas>
                <latitud unidades="grados">-8.8947449984732</latitud>
                <longitud unidades="grados">116.30847784104657</longitud>
                <altitud unidades="metros">7.57</altitud>
            </coordenadas>
            <distancia unidades="metros">15.34</distancia>
        </tramo>
        <tramo sector="S1">
            <coordenadas>
                <latitud unidades="grados">-8.89487991703092</latitud>
                <longitud unidades="grados">116.3085102432023</longitud>
                <altitud unidades="metros">7.95</altitud>
            </coordenadas>
            <distancia unidades="metros">31.32</distancia>
        </tramo>
        <tramo sector="S1">
            <coordenadas>
                <latitud unidades="grados">-8.895162878028287</latitud>
                <longitud unidades="grados">116.30852049181601</longitud>
                <altitud unidades="metros">8.09</altitud>
            </coordenadas>
            <distancia unidades="metros">77.55</distancia>
        </tramo>
        <tramo sector="S1">
            <coordenadas>
                <latitud unidades="grados">-8.895863793092374</latitud>
                <longitud unidades="grados">116.30853897032216</longitud>
                <altitud unidades="metros">8.01</altitud>
            </coordenadas>
            <distancia unidades="metros">85.65</distancia>
        </tramo>
        <tramo sector="S1">
            <coordenadas>
                <latitud unidades="grados">-8.89663759180553</latitud>
                <longitud unidades="grados">116.30857092611183</longitud>
                <altitud unidades="metros">7.59</altitud>
            </coordenadas>
            <distancia unidades="metros">15.82</distancia>
        </tramo>
        <tramo sector="S1">
            <coordenadas>
                <latitud unidades="grados">-8.896775584305715</latitud>
                <longitud unidades="grados">116.30853310950124</longitud>
                <altitud unidades="metros">7.49</altitud>
            </coordenadas>
            <distancia unidades="metros">13.67</distancia>
        </tramo>
        <tramo sector="S1">
            <coordenadas>
                <latitud unidades="grados">-8.896879698879118</latitud>
                <longitud unidades="grados">116.30846606510221</longitud>
                <altitud unidades="metros">7.24</altitud>
            </coordenadas>
            <distancia unidades="metros">19.96</distancia>
        </tramo>
        <tramo sector="S1">
            <coordenadas>
                <latitud unidades="grados">-8.896976838733764</latitud>
                <longitud unidades="grados">116.30831313887035</longitud>
                <altitud unidades="metros">7.7</altitud>
            </coordenadas>
            <distancia unidades="metros">44.09</distancia>
        </tramo>
        <tramo sector="S1">
            <coordenadas>
                <latitud unidades="grados">-8.896999193833452</latitud>
                <longitud unidades="grados">116.30791291840086</longitud>
                <altitud unidades="metros">7.49</altitud>
            </coordenadas>
            <distancia unidades="metros">13.61</distancia>
        </tramo>
        <tramo sector="S1">
            <coordenadas>
                <latitud unidades="grados">-8.897055795779323</latitud>
                <longitud unidades="grados">116.3078029996143</longitud>
                <altitud unidades="metros">7.37</altitud>
            </coordenadas>
            <distancia unidades="metros">52.67</distancia>
        </tramo>
        <tramo sector="S1">
            <coordenadas>
                <latitud unidades="grados">-8.89747402621282</latitud>
                <longitud unidades="grados">116.307574018774</longitud>
                <altitud unidades="metros">7.5</altitud>
            </coordenadas>
            <distancia unidades="metros">16.42</distancia>
        </tramo>
        <tramo sector="S1">
            <coordenadas>
                <latitud unidades="grados">-8.897622445405801</latitud>
                <longitud unidades="grados">116.30757388561813</longitud>
                <altitud unidades="metros">7.37</altitud>
            </coordenadas>
            <distancia unidades="metros">11.62</distancia>
        </tramo>
        <tramo sector="S1">
            <coordenadas>
                <latitud unidades="grados">-8.897718537687823</latitud>
                <longitud unidades="grados">116.30761649857652</longitud>
